### PR TITLE
Handle Ctrl and Cmd in keyboard events

### LINKED ISSUE #17: Keyboard shortcuts not working on Windows
**Describe the bug**
I'm unable to pull up the control panel in Windows. In fact, all of these don't work:

- command-k: Toggle control panel
- command-shift-enter: Start presentation (from first slide)
- command-enter: Resume presentation (from active slide)
- command-shift-f: Toggle full-screen mode
- command-.: End presentation

**To Reproduce**
Open the demo site in Windows and try any of the shortcuts above. Nothing happens

**Expected behaviour**
The action associated with each shortcut happens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, Edge, and Firefox

### PR DESCRIPTION
**Pull request by jerivas**
## Related Issue(s)
Fixes #17

## Steps to test/reproduce
Use either Cmd or Ctrl for keyboard shortcuts

### CODE REVIEW

File: slide-deck.js [hunk 1]
```diff
@@ -455,9 +455,12 @@ class slideDeck extends HTMLElement {
     this.goTo(this.slideFromStore());
   }
 
+  // Detect Ctrl / Cmd modifiers in a platform-agnostic way
+  cmdOrCtrl = (event) => event.ctrlKey || event.metaKey;
```
Comment (jerivas) [inline slide-deck.js:459]: We could try to be clever and do platform sniffing to respond to only one of this, but from a quick investigation and issues like [this](https://github.com/vuejs/vue/issues/4843), it seems like just handling both should be enough.

**Review by mirisuzanne — APPROVED** [review]
Code looks good, and it still works on mac :)

File: slide-deck.js (hunk 1 above)
Comment (jamesnw) [inline slide-deck.js:459]: I think this should be a private method (the other PR is making most of the others private, so this would match that, eventually).

**Review by jamesnw — APPROVED** [review]
LGTM 🚀

**Review by dvdherron — APPROVED** [review]
Works great! I think the only shortcut that I couldn't get to work was `ctrl + shift + f` for toggling full screen mode but otherwise this works great.

**Comment by mirisuzanne** [comment]
> Works great! I think the only shortcut that I couldn't get to work was `ctrl + shift + f` for toggling full screen mode but otherwise this works great.

@dvdherron What browser are you using, and what shows in the console when you try it? Any chance you're running into #1

**Comment by dvdherron** [comment]
> > Works great! I think the only shortcut that I couldn't get to work was `ctrl + shift + f` for toggling full screen mode but otherwise this works great.
> 
> @dvdherron What browser are you using, and what shows in the console when you try it? Any chance you're running into #1

Hmm. That's interesting. I get the same response in Chrome and Firefox. I tried this with the `caps'lock` key on and it worked in both browsers.

**Comment by mirisuzanne** [comment]
> Hmm. That's interesting. I get the same response in Chrome and Firefox. I tried this with the `caps-lock` key on and it worked in both browsers.

Strange. I'm not sure how to debug that. I'm also not sure if this is the right shortcut for fullscreen.

> And once I get the slides to go fullscreen with the shortcut I can only see the first slide. Is that expected?

Nope. But that seems like a separate issue we can add to the fullscreen issue pile.

**Comment by mirisuzanne** [comment]
I'd be real tempted to merge this and remove fullscreen support until we can get it working correctly. Fullscreen is not a feature that I expect to use in the workshop.
